[package]
name = "secret-rare/filoxen-luau"
version = "0.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]
RbxAssetUtils = "secret-rare/rbx-asset-utils@0.2.0"
